(function(){
'use strict';
var cfg=window.DRAVYAGUNA_FIREBASE_CONFIG||{};
var auth=null,db=null,user=null;
var V='10.12.5';
function configured(){return cfg.apiKey&&cfg.apiKey.indexOf('REPLACE_')!==0&&cfg.projectId&&cfg.projectId.indexOf('REPLACE_')!==0&&cfg.appId&&cfg.appId.indexOf('REPLACE_')!==0}
function context(){return {page_url:location.href,page_path:location.pathname+location.search,page_title:document.title,referrer:document.referrer||'',language:navigator.language||'',platform:navigator.platform||'',user_agent:navigator.userAgent||'',screen_width:screen.width||0,screen_height:screen.height||0,timestamp:new Date().toISOString()}}
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function mount(){var main=document.querySelector('main');if(!main||document.getElementById('dgFeedbackMount'))return;var old=document.querySelector('.review-section');if(old)old.style.display='none';var s=document.createElement('section');s.id='dgFeedbackMount';s.innerHTML='<div class="dg-feedback-card"><div class="dg-feedback-head"><div class="review-badge">💬 Verified Feedback</div><h2>Help Improve DravyaGuna 97</h2><p>Sign in with Google before submitting feedback.</p></div><div id="dgLogin"></div><form id="dgFeedbackForm" class="dg-hidden"><div class="dg-feedback-grid"><div class="dg-field"><label for="dgCategory">Feedback Type</label><select id="dgCategory" required><option value="content">Content Correction</option><option value="bug">Technical Bug</option><option value="feature">Feature Request</option><option value="general">General Feedback</option></select></div><div class="dg-field"><label>Rating</label><div class="dg-stars"><input required type="radio" name="dgRating" value="1" id="dgR1"><label for="dgR1">★ 1</label><input type="radio" name="dgRating" value="2" id="dgR2"><label for="dgR2">★ 2</label><input type="radio" name="dgRating" value="3" id="dgR3"><label for="dgR3">★ 3</label><input type="radio" name="dgRating" value="4" id="dgR4"><label for="dgR4">★ 4</label><input type="radio" name="dgRating" value="5" id="dgR5"><label for="dgR5">★ 5</label></div></div><div class="dg-field full"><label for="dgMessage">Feedback Details</label><textarea id="dgMessage" maxlength="2000" required placeholder="Tell us what should be corrected or improved..."></textarea></div><div class="dg-field"><label for="dgCorrection">Correction area</label><select id="dgCorrection"><option value="">Not applicable</option><option>Botanical identity</option><option>Sanskrit name/reference</option><option>Rasa Panchaka</option><option>Pharmacological action</option><option>Therapeutic uses</option><option>Formulation</option><option>Plant identification/images</option><option>Other</option></select></div><div class="dg-field"><label for="dgEmail">Verified Google email</label><input id="dgEmail" type="email" readonly></div></div><button type="submit" class="dg-submit" id="dgSubmit">Submit Verified Feedback</button><div id="dgStatus" class="dg-status" role="status"></div><p class="dg-note">We store your Google account name, Gmail address, Google account ID, profile photo when available, and submission context with the review for moderation and follow-up.</p></form></div>';main.appendChild(s);loginUI()}
function loadFirebase(){return Promise.all(['firebase-app.js','firebase-auth.js','firebase-firestore.js'].map(function(n){return new Promise(function(ok,no){var x=document.createElement('script');x.src='https://www.gstatic.com/firebasejs/'+V+'/'+n;x.onload=ok;x.onerror=no;document.head.appendChild(x)})})).then(function(){if(window.firebase.apps&&window.firebase.apps.length)window.firebase.app();else window.firebase.initializeApp(cfg);auth=window.firebase.auth();db=window.firebase.firestore();auth.onAuthStateChanged(function(u){user=u||null;loginUI()})})}
function loginUI(){var e=document.getElementById('dgLogin'),f=document.getElementById('dgFeedbackForm');if(!e||!f)return;if(user){e.innerHTML='<div class="dg-feedback-login"><div class="dg-user">'+(user.photoURL?'<img src="'+esc(user.photoURL)+'" alt="">':'👤')+'<div class="dg-user-text"><strong>'+esc(user.displayName||'Google user')+'</strong><span>'+esc(user.email||'')+'</span></div></div><button type="button" class="dg-signout" id="dgSignout">Sign out</button></div>';f.classList.remove('dg-hidden');document.getElementById('dgEmail').value=user.email||'';document.getElementById('dgSignout').onclick=function(){auth.signOut()};bindForm()}else{e.innerHTML='<div class="dg-feedback-login"><div><strong>Google verification required</strong><div style="font-size:.9rem;color:var(--muted)">Your browser does not expose your Gmail login automatically. Sign in with Google to verify the account.</div></div><button type="button" class="dg-google-btn" id="dgGoogle">🔐 Continue with Google</button></div>';f.classList.add('dg-hidden');document.getElementById('dgGoogle').onclick=function(){var p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});auth.signInWithPopup(p).catch(function(x){show(x.message||'Google sign-in failed.',true)})}}}
function show(t,bad){var e=document.getElementById('dgStatus');if(!e)return;e.textContent=t;e.className='dg-status show '+(bad?'err':'ok')}
function bindForm(){var f=document.getElementById('dgFeedbackForm');if(!f||f.dataset.bound)return;f.dataset.bound='1';f.addEventListener('submit',function(ev){ev.preventDefault();if(!user)return show('Please sign in with Google first.',true);var btn=document.getElementById('dgSubmit');btn.disabled=true;var checked=f.querySelector('input[name="dgRating"]:checked');if(!checked){btn.disabled=false;return show('Please select a rating.',true)}var payload={category:document.getElementById('dgCategory').value,rating:Number(checked.value),message:document.getElementById('dgMessage').value.trim(),correction_area:document.getElementById('dgCorrection').value||null,user:{uid:user.uid,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null},context:context(),status:'new',createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(!payload.message){btn.disabled=false;return show('Please enter feedback details.',true)}db.collection('reviews').add(payload).then(function(){return db.collection('reviewUsers').doc(user.uid).set({uid:user.uid,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null,lastSubmittedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){f.reset();document.getElementById('dgEmail').value=user.email||'';btn.disabled=false;show('Thank you! Your verified feedback has been recorded.',false)}).catch(function(){btn.disabled=false;show('Could not submit feedback. Please try again.',true)})})}
function init(){mount();if(configured())loadFirebase().catch(function(){show('Feedback service could not be loaded. Check Firebase configuration and authorized domains.',true)});else{var e=document.getElementById('dgLogin');if(e)e.innerHTML='<div class="dg-feedback-login"><div><strong>Feedback system setup required</strong><div style="font-size:.9rem;color:var(--muted)">The site is ready for verified Google feedback. The site owner must connect the Firebase project before submissions can be accepted.</div></div></div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
