(function(){
'use strict';
var cfg=window.DRAVYAGUNA_FIREBASE_CONFIG||{},auth=null,db=null,user=null;
var V='10.12.5';

function configured(){return cfg.apiKey&&cfg.apiKey.indexOf('REPLACE_')!==0&&cfg.projectId&&cfg.projectId.indexOf('REPLACE_')!==0&&cfg.appId&&cfg.appId.indexOf('REPLACE_')!==0}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function context(){return{page_url:location.href,page_path:location.pathname+location.search,page_title:document.title,referrer:document.referrer||'',language:navigator.language||'',timestamp:new Date().toISOString()}}
function setStatus(t,type){var e=document.getElementById('dgStatus');if(!e)return;e.textContent=t;e.className='dg-status show '+(type||'')}
function setBusy(b){var btn=document.getElementById('dgSubmit');if(btn){btn.disabled=b;btn.setAttribute('aria-busy',b?'true':'false');btn.innerHTML=b?'<span class="dg-spinner" aria-hidden="true"></span><span>Submitting…</span>':'<span>Submit feedback</span><span aria-hidden="true">→</span>'}}
function mount(){
 var main=document.querySelector('main'),mount=document.getElementById('reviews');if(!main||!mount||mount.dataset.mounted)return;mount.dataset.mounted='1';
 mount.innerHTML='<div class="dg-feedback-card"><div class="dg-feedback-copy"><span class="dg-feedback-badge">💬 VERIFIED FEEDBACK</span><h2>Help improve DravyaGuna 97</h2><p>Found an error, missing information, or have an idea? Tell us what to improve. Your feedback is linked to your verified Google account to reduce spam.</p><div class="dg-feedback-points"><span>✓ Content corrections</span><span>✓ Bug reports</span><span>✓ Feature ideas</span></div></div><div class="dg-feedback-panel"><div id="dgLogin"></div><form id="dgFeedbackForm" class="dg-hidden" novalidate><div class="dg-feedback-grid"><div class="dg-field"><label for="dgCategory">Feedback type <span>*</span></label><select id="dgCategory" required><option value="content">Content correction</option><option value="bug">Technical bug</option><option value="feature">Feature request</option><option value="general">General feedback</option></select></div><div class="dg-field"><label for="dgRating">Experience rating <span>*</span></label><div class="dg-rating" role="radiogroup" aria-label="Rate your experience"><button type="button" data-rating="1" aria-label="1 star">★</button><button type="button" data-rating="2" aria-label="2 stars">★</button><button type="button" data-rating="3" aria-label="3 stars">★</button><button type="button" data-rating="4" aria-label="4 stars">★</button><button type="button" data-rating="5" aria-label="5 stars">★</button></div><input type="hidden" id="dgRating" required></div><div class="dg-field full"><label for="dgMessage">Your feedback <span>*</span></label><textarea id="dgMessage" maxlength="2000" required placeholder="Example: The botanical name on Amalaki needs correction…"></textarea><div class="dg-field-meta"><span>Be specific so we can act on it.</span><span><b id="dgCount">0</b>/2000</span></div></div><div class="dg-field"><label for="dgCorrection">Area (optional)</label><select id="dgCorrection"><option value="">Select an area</option><option>Botanical identity</option><option>Sanskrit name/reference</option><option>Rasa Panchaka</option><option>Pharmacological action</option><option>Therapeutic uses</option><option>Formulation</option><option>Plant identification/images</option><option>Other</option></select></div><div class="dg-field"><label for="dgEmail">Verified account</label><input id="dgEmail" type="email" readonly aria-readonly="true"></div></div><button type="submit" class="dg-submit" id="dgSubmit"><span>Submit feedback</span><span aria-hidden="true">→</span></button><div id="dgStatus" class="dg-status" role="status" aria-live="polite"></div><p class="dg-note">🔒 Your Google account is used for verification. We store your account ID, name, email, optional profile photo, feedback and page context for moderation. We do not display your email publicly.</p></form></div></div>';
 bindRating();bindCount();loginUI();
}
function bindRating(){var box=document.querySelector('.dg-rating');if(!box)return;box.addEventListener('click',function(e){var b=e.target.closest('button[data-rating]');if(!b)return;var n=Number(b.dataset.rating);document.getElementById('dgRating').value=n;box.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',Number(x.dataset.rating)<=n);x.setAttribute('aria-checked',Number(x.dataset.rating)===n?'true':'false')});box.classList.remove('invalid')})}
function bindCount(){var t=document.getElementById('dgMessage'),c=document.getElementById('dgCount');if(!t||!c)return;t.addEventListener('input',function(){c.textContent=t.value.length})}
function loadFirebase(){return Promise.all(['firebase-app.js','firebase-auth.js','firebase-firestore.js'].map(function(n){return new Promise(function(ok,no){var x=document.createElement('script');x.src='https://www.gstatic.com/firebasejs/'+V+'/'+n;x.onload=ok;x.onerror=no;document.head.appendChild(x)})})).then(function(){if(window.firebase.apps&&window.firebase.apps.length)window.firebase.app();else window.firebase.initializeApp(cfg);auth=window.firebase.auth();db=window.firebase.firestore();auth.onAuthStateChanged(function(u){user=u||null;loginUI()})})}
function loginUI(){
 var e=document.getElementById('dgLogin'),f=document.getElementById('dgFeedbackForm');if(!e||!f)return;
 if(user){
  e.innerHTML='<div class="dg-feedback-login"><div class="dg-user"><div class="dg-avatar">'+(user.photoURL?'<img src="'+esc(user.photoURL)+'" alt="">':'👤')+'</div><div class="dg-user-text"><strong>'+esc(user.displayName||'Google user')+'</strong><span>'+esc(user.email||'')+'</span></div></div><button type="button" class="dg-signout" id="dgSignout">Sign out</button></div>';
  f.classList.remove('dg-hidden');document.getElementById('dgEmail').value=user.email||'';document.getElementById('dgSignout').onclick=function(){auth.signOut()};bindForm();
 }else{
  e.innerHTML='<div class="dg-feedback-login dg-login-prompt"><div><strong>Sign in to send feedback</strong><span>Google verification keeps the feedback channel reliable and spam-resistant.</span></div><button type="button" class="dg-google-btn" id="dgGoogle"><span aria-hidden="true">G</span> Continue with Google</button></div>';
  f.classList.add('dg-hidden');document.getElementById('dgGoogle').onclick=function(){var p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});setStatus('Opening Google sign-in…','loading');auth.signInWithPopup(p).catch(function(x){setStatus(x.message||'Google sign-in failed. Please try again.','err')})};
 }
}
function bindForm(){
 var f=document.getElementById('dgFeedbackForm');if(!f||f.dataset.bound)return;f.dataset.bound='1';
 f.addEventListener('submit',function(ev){
  ev.preventDefault();if(!user)return setStatus('Please sign in with Google first.','err');
  var rating=Number(document.getElementById('dgRating').value),message=document.getElementById('dgMessage').value.trim();
  if(!rating){document.querySelector('.dg-rating').classList.add('invalid');return setStatus('Please select a rating.','err')}
  if(!message)return setStatus('Please enter your feedback details.','err');
  setBusy(true);
  var payload={category:document.getElementById('dgCategory').value,rating:rating,message:message,correction_area:document.getElementById('dgCorrection').value||null,user:{uid:user.uid,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null},context:context(),status:'new',createdAt:firebase.firestore.FieldValue.serverTimestamp()};
  db.collection('reviews').add(payload).then(function(){return db.collection('reviewUsers').doc(user.uid).set({uid:user.uid,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null,lastSubmittedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){f.reset();document.getElementById('dgRating').value='';document.getElementById('dgCount').textContent='0';document.querySelectorAll('.dg-rating button').forEach(function(x){x.classList.remove('active');x.setAttribute('aria-checked','false')});document.getElementById('dgEmail').value=user.email||'';setBusy(false);setStatus('Thanks! Your verified feedback has been submitted.','ok');setTimeout(function(){var s=document.getElementById('dgStatus');if(s)s.className='dg-status'},5000)}).catch(function(err){console.error('Feedback submission failed',err);setBusy(false);setStatus('Could not submit feedback right now. Please try again.','err')})
 })
}
function init(){mount();if(configured())loadFirebase().catch(function(){setStatus('Feedback service could not be loaded. Please try again later.','err')});else{var e=document.getElementById('dgLogin');if(e)e.innerHTML='<div class="dg-feedback-login"><div><strong>Feedback setup is incomplete</strong><span>The site owner needs to finish the Firebase connection before feedback can be submitted.</span></div></div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();