(function(){
'use strict';
var cfg=window.DRAVYAGUNA_FIREBASE_CONFIG||{},auth=null,db=null,user=null,firebaseReady=false,V='10.12.5';

function configured(){return !!(cfg.apiKey&&cfg.projectId&&cfg.appId&&cfg.apiKey.indexOf('REPLACE_')!==0&&cfg.projectId.indexOf('REPLACE_')!==0&&cfg.appId.indexOf('REPLACE_')!==0)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function context(){return{page_url:location.href,page_path:location.pathname+location.search,page_title:document.title,referrer:document.referrer||'',language:navigator.language||'',timestamp:new Date().toISOString()}}
function status(t,type){var e=document.getElementById('dgStatus');if(e){e.textContent=t;e.className='dg-status show '+(type||'')}}
function busy(v){var b=document.getElementById('dgSubmit');if(!b)return;b.disabled=v;b.innerHTML=v?'<span class="dg-spinner" aria-hidden="true"></span><span>Submitting…</span>':'<span>Submit feedback</span><span aria-hidden="true">→</span>'}
function mount(){
 var mount=document.getElementById('reviews');if(!mount||mount.dataset.mounted)return;mount.dataset.mounted='1';
 mount.innerHTML='<div class="dg-feedback-card"><div class="dg-feedback-copy"><span class="dg-feedback-badge">💬 FEEDBACK</span><h2>Help improve DravyaGuna 97</h2><p>Report an error, missing information, technical bug or feature idea. Feedback can now be sent without creating an account; Google sign-in remains available as an optional identity check.</p><div class="dg-feedback-points"><span>✓ Content corrections</span><span>✓ Bug reports</span><span>✓ Feature ideas</span></div></div><div class="dg-feedback-panel"><div id="dgLogin"></div><form id="dgFeedbackForm" novalidate><div class="dg-feedback-grid"><div class="dg-field"><label for="dgCategory">Feedback type <span>*</span></label><select id="dgCategory" required><option value="content">Content correction</option><option value="bug">Technical bug</option><option value="feature">Feature request</option><option value="general">General feedback</option></select></div><div class="dg-field"><label for="dgRating">Experience rating <span>*</span></label><div class="dg-rating" role="radiogroup" aria-label="Rate your experience"><button type="button" data-rating="1" aria-label="1 star">★</button><button type="button" data-rating="2" aria-label="2 stars">★</button><button type="button" data-rating="3" aria-label="3 stars">★</button><button type="button" data-rating="4" aria-label="4 stars">★</button><button type="button" data-rating="5" aria-label="5 stars">★</button></div><input type="hidden" id="dgRating"></div><div class="dg-field full"><label for="dgMessage">Your feedback <span>*</span></label><textarea id="dgMessage" maxlength="2000" required placeholder="Example: The botanical name on Amalaki needs correction…"></textarea><div class="dg-field-meta"><span>Be specific so we can act on it.</span><span><b id="dgCount">0</b>/2000</span></div></div><div class="dg-field"><label for="dgCorrection">Area (optional)</label><select id="dgCorrection"><option value="">Select an area</option><option>Botanical identity</option><option>Sanskrit name/reference</option><option>Rasa Panchaka</option><option>Therapeutic uses</option><option>Formulation</option><option>Plant identification/images</option><option>Other</option></select></div><div class="dg-field"><label for="dgEmail">Account</label><input id="dgEmail" type="text" readonly value="Anonymous feedback"></div></div><button type="submit" class="dg-submit" id="dgSubmit"><span>Submit feedback</span><span aria-hidden="true">→</span></button><div id="dgStatus" class="dg-status" role="status" aria-live="polite"></div><p class="dg-note">🔒 Feedback is stored privately in Firestore. Your email is stored only when you voluntarily sign in with Google.</p></form></div></div>';
 document.querySelectorAll('.dg-rating button').forEach(function(b){b.addEventListener('click',function(){var n=Number(b.dataset.rating),box=b.parentElement;document.getElementById('dgRating').value=n;box.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',Number(x.dataset.rating)<=n);x.setAttribute('aria-checked',Number(x.dataset.rating)===n?'true':'false')})})});
 var msg=document.getElementById('dgMessage'),count=document.getElementById('dgCount');msg.addEventListener('input',function(){count.textContent=msg.value.length});
 document.getElementById('dgFeedbackForm').addEventListener('submit',submit);
}
function loginUI(){
 var e=document.getElementById('dgLogin');if(!e)return;
 if(!user){e.innerHTML='<div class="dg-feedback-login"><div><strong>Feedback service is connecting…</strong><span>You can submit anonymously. Google sign-in is optional.</span></div><button type="button" class="dg-google-btn" id="dgGoogle">Sign in with Google</button></div>';var b=document.getElementById('dgGoogle');if(b)b.onclick=googleLogin;return}
 var anon=!!user.isAnonymous;
 e.innerHTML='<div class="dg-feedback-login"><div class="dg-user"><div class="dg-avatar">'+(user.photoURL?'<img src="'+esc(user.photoURL)+'" alt="">':'👤')+'</div><div class="dg-user-text"><strong>'+(anon?'Anonymous visitor':esc(user.displayName||'Google user'))+'</strong><span>'+(anon?'No account required':esc(user.email||''))+'</span></div></div>'+(anon?'<button type="button" class="dg-signout" id="dgGoogle">Use Google</button>':'<button type="button" class="dg-signout" id="dgSignout">Sign out</button>')+'</div>';
 if(anon)document.getElementById('dgGoogle').onclick=googleLogin;else document.getElementById('dgSignout').onclick=function(){auth.signOut().then(function(){return auth.signInAnonymously()})};
 var em=document.getElementById('dgEmail');if(em)em.value=anon?'Anonymous feedback':(user.email||'Google account');
}
function loadFirebase(){
 return Promise.all(['firebase-app-compat.js','firebase-auth-compat.js','firebase-firestore-compat.js'].map(function(n){return new Promise(function(ok,no){var s=document.createElement('script');s.src='https://www.gstatic.com/firebase/'+V+'/'+n;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}))
 .then(function(){if(window.firebase.apps&&window.firebase.apps.length)window.firebase.app();else window.firebase.initializeApp(cfg);auth=window.firebase.auth();db=window.firebase.firestore();auth.onAuthStateChanged(function(u){user=u||null;loginUI()});return auth.signInAnonymously().catch(function(e){console.warn('Anonymous auth unavailable',e);loginUI();})})
}
function googleLogin(){
 if(!firebaseReady||!auth)return status('Feedback service is still loading. Please try again.','err');
 var p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});status('Opening Google sign-in…','loading');
 auth.signInWithPopup(p).catch(function(e){console.error('Google sign-in failed',e);if(e&&['auth/popup-blocked','auth/popup-closed-by-user','auth/cancelled-popup-request'].indexOf(e.code)>=0)return auth.signInWithRedirect(p);status(e&&e.message||'Google sign-in failed. Anonymous feedback is still available.','err')});
}
function submit(ev){
 ev.preventDefault();if(!user)return status('Feedback service is not connected yet. Please refresh once.','err');
 var rating=Number(document.getElementById('dgRating').value),message=document.getElementById('dgMessage').value.trim();
 if(!rating){document.querySelector('.dg-rating').classList.add('invalid');return status('Please select a rating.','err')}
 if(!message)return status('Please enter your feedback details.','err');
 if(message.length>2000)return status('Feedback is limited to 2000 characters.','err');
 busy(true);
 var payload={category:document.getElementById('dgCategory').value,rating:rating,message:message.slice(0,2000),correction_area:document.getElementById('dgCorrection').value||null,user:{uid:user.uid,isAnonymous:!!user.isAnonymous,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null},context:context(),status:'new',createdAt:firebase.firestore.FieldValue.serverTimestamp()};
 db.collection('reviews').add(payload).then(function(){return db.collection('reviewUsers').doc(user.uid).set({uid:user.uid,isAnonymous:!!user.isAnonymous,displayName:user.displayName||null,email:user.email||null,emailVerified:!!user.emailVerified,photoURL:user.photoURL||null,lastSubmittedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}).then(function(){document.getElementById('dgFeedbackForm').reset();document.getElementById('dgRating').value='';document.getElementById('dgCount').textContent='0';document.querySelectorAll('.dg-rating button').forEach(function(x){x.classList.remove('active')});busy(false);status('Thanks! Your feedback has been submitted.','ok')}).catch(function(e){console.error('Feedback submission failed',e);busy(false);status('Could not submit feedback. Please try again.','err')})
}
function init(){mount();if(!configured()){status('Feedback setup is incomplete.','err');return}loadFirebase().then(function(){firebaseReady=true;loginUI()}).catch(function(e){console.error(e);status('Feedback service could not be loaded.','err')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();