import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'plants.json'
RECORDS=[
{"id":84,"name":"Chitraka","category":"NCISM-97","botanical_name":"Plumbago zeylanica L.","family":"Plumbaginaceae","english_name":"Leadwort / White Leadwort","sanskrit_synonyms":["Agni (अग्नि)","Dahana (दहन)","Pathi (पथि)","Shikhi (शिखी)","Anala (अनल)"],"useful_part":"Root bark (Mula Twak)","rasa":["Katu"],"guna":["Laghu","Ruksha","Tikshna"],"virya":"Ushna","vipaka":"Katu","prabhava":"Agrya Deepaniya Dravya / Pachana / Arshoghna","dosha":"Kapha-Vatashamaka","karma":["Deepana","Pachana","Grahi","Shothahara","Arshoghna","Shoolaprashamana","Krimighna","Bhedana"],"indications":["Agnimandya (Loss of appetite / Dyspepsia)","Grahani (Irritable bowel syndrome / Malabsorption)","Arsha (Hemorrhoids)","Shotha (Edema / Swelling)","Shoola (Abdominal colic)","Udara Roga (Ascites / Abdominal enlargement)"],"formulations":["Chitrakadi Vati","Chitrak Haritaki","Chitrakadi Churna","Chitrak Ghrita","Kankayana Vati"],"identification":"Cylindrical brownish-grey roots with striations and rootlet scars, acrid biting persistent burning taste causing intense tingling on tongue, distinct pungent odor.","shloka":"चित्रकोऽग्निसमः पाके कटुकः कफवातजित्।\nशोथअर्ंशःकृमिहा दीपनः पाचकः सरः॥","source":{"text_grantha_name":"Bhavaprakasha Nighantu","varga_chapter":"Haritakyadi Varga","shloka_number":"Verse 70-72","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification":"A. Directly verified classical reference"},
{"id":85,"name":"Bhallataka","category":"NCISM-97","botanical_name":"Semecarpus anacardium L.f.","family":"Anacardiaceae","english_name":"Marking Nut / Clearing Nut","sanskrit_synonyms":["Arushkara (अरुष्कर)","Agnimukhi (अग्निमुखी)","Shailabija (शैलबीज)","Tapana (तपन)","Vishasphota (विषस्फोट)"],"useful_part":"Purified Fruit pericarp / Nut (Shodhita Phala / Seed oil)","rasa":["Katu","Tikta","Kashaya"],"guna":["Laghu","Tikshna","Snigdha"],"virya":"Ushna","vipaka":"Katu","prabhava":"Chedana / Rasayana / Vrana-rohana / Arshoghna","dosha":"Kapha-Vatashamaka","karma":["Deepana","Pachana","Chedana","Bhedana","Rasayana","Vrishya","Kushtaghna","Krimighna"],"indications":["Arsha (Bleeding and non-bleeding hemorrhoids)","Kushta (Chronic skin diseases / Psoriasis)","Shotha (Edema)","Gulma (Abdominal tumors / Masses)","Kaphaja Roga (Severe Kapha disorders)","Grdhrasi (Sciatica)"],"formulations":["Sanjivani Vati","Bhallataka Rasayana","Amrita Bhallataka Lehya","Bhallatakadi Taila","Bhallatakadi Asava"],"identification":"Heart-shaped or ovoid dark shiny black drupe seated on an orange-yellow fleshy receptacle (receptacle edible), pericarp filled with corrosive black vesicating juice.","shloka":"भल्लातकः कटुस्तिक्तः कषायोष्णो लघुः सरः।\nदीपनः पाचनश्चैव कफवातहरो मतः॥","source":{"text_grantha_name":"Bhavaprakasha Nighantu","varga_chapter":"Haritakyadi Varga","shloka_number":"Verse 63-65","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification":"A. Directly verified classical reference"},
{"id":86,"name":"Gunja","category":"Supplementary","botanical_name":"Abrus precatorius L.","family":"Fabaceae (Papilionaceae)","english_name":"Rosary Pea / Jequirity Bean","sanskrit_synonyms":["Raktika (रक्तिका)","Kakananti (काकणन्ती)","Chudamani (चूडामणि)","Shikhandini (शिखण्डिनी)","Kakachinchi (काकचिञ्ची)"],"useful_part":"Purified Seeds (Shodhita Bija), Leaves (Patra), Root (Mula)","rasa":["Tikta","Kashaya"],"guna":["Laghu","Ruksha","Tikshna"],"virya":"Ushna","vipaka":"Katu","prabhava":"Keshya / Vishaghna / Kandughna","dosha":"Kapha-Vatashamaka","karma":["Keshya","Vishaghna","Vrana-shodhaka","Kandughna","Balya","Vrishya","Vranarohana"],"indications":["Indralupta (Alopecia areata / Hair loss)","Kushta (Skin diseases)","Kandu (Pruritus / Itching)","Vrana (Chronic non-healing ulcers)","Shiro-shoola (Headache / Hemicrania)"],"formulations":["Gunja Taila","Gunjadi Lepa","Gunjadi Taila","Mahavishagarbha Taila"],"identification":"Hard egg-shaped glossy seeds, bright scarlet red with a distinctive black mark at the hilum (Rakta Gunja) or glossy milk-white with black mark (Shweta Gunja), highly poisonous unpurified.","shloka":"गुञ्जा द्वया तु तिक्तोष्णा कषाया कफवातजित्।\nचक्षुष्या केशिया वृष्या च विषव्रणविनाशिनी॥","source":{"text_grantha_name":"Bhavaprakasha Nighantu","varga_chapter":"Guduchyadi Varga","shloka_number":"Verse 236-237","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification":"A. Directly verified classical reference"},
{"id":87,"name":"Jayapala","category":"Supplementary","botanical_name":"Croton tiglium L.","family":"Euphorbiaceae","english_name":"Purging Croton","sanskrit_synonyms":["Rechaka (रेचक)","Kumbhini (कुम्भिनी)","Danti-bija (दन्तीबीज)","Nikumbha (निकुम्भ)","Tintidiphala (तिन्तिडीफल)"],"useful_part":"Purified Seed (Shodhita Bija)","rasa":["Katu"],"guna":["Laghu","Tikshna","Ruksha","Vyavayi","Vikasi"],"virya":"Ushna","vipaka":"Katu","prabhava":"Tivra-Rechana (Druta Virechana / Hydragogue Cathartic)","dosha":"Kapha-Pittashamaka","karma":["Tivra-Virechana","Deepana","Rechana","Kaphaghna","Shothahara","Krimighna"],"indications":["Vibandha (Severe stubborn constipation)","Udara Roga (Ascites / Abdominal disorders)","Jalodara (Dropsy / Abdominal fluid retention)","Shotha (Severe systemic edema)","Unmada (Psychosis / Mania)","Kaphaja Gulma (Abdominal masses)"],"formulations":["Ichhabhedi Rasa","Jalodarari Rasa","Anand Bhairav Rasa","Mahamrityunjaya Rasa"],"identification":"Oval 3-angled dark dull brownish seeds with a thin brittle outer test enclosing an oily pale yellow kernel, intensely acrid taste causing severe burning throat irritation.","shloka":"जयपालोऽतिरेची स्यात् कटुरुष्णश्च तीक्ष्णकः।\nकफपित्तहरो दीपी शोथोदरविनाशनः॥","source":{"text_grantha_name":"Bhavaprakasha Nighantu","varga_chapter":"Guduchyadi Varga","shloka_number":"Verse 200-202","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification":"A. Directly verified classical reference"},
{"id":88,"name":"Dhattura","category":"Supplementary","botanical_name":"Datura metel L.","family":"Solanaceae","english_name":"Thorn Apple / Downy Datura","sanskrit_synonyms":["Kanaka (कनक)","Umatta (उमत्त)","Kitava (कितव)","Madana (मदन)","Shivapriya (शिवप्रिय)"],"useful_part":"Purified Seed (Shodhita Bija), Leaf (Patra), Root (Mula)","rasa":["Tikta","Katu"],"guna":["Laghu","Ruksha","Tikshna","Vikasi","Vyavayi"],"virya":"Ushna","vipaka":"Katu","prabhava":"Madakari / Vedanasthapana / Shoolahara / Kasahara","dosha":"Kapha-Vatashamaka","karma":["Vedanasthapana","Shoolaprashamana","Kasahara","Swasahara","Madakari","Kandughna","Krimighna"],"indications":["Shwasa (Bronchial asthma / Dyspnea)","Kasa (Cough / Spasmodic bronchitis)","Sandhishoola (Joint pain / Rheumatic pain)","Kushta (Skin diseases)","Juuka (Lice infestation / Scalp infections)","Unmada (Delirium / Agitation)"],"formulations":["Kanakasava","Dhattura Taila","Mahavishagarbha Taila","Laxmi Vilas Rasa","Tribhuvan Kirti Rasa"],"identification":"Flat kidney-shaped light yellowish-brown seeds with reticulated test, globose spinous capsule fruit, characteristic unpleasantly heavy narcotic odor and bitter acrid taste.","shloka":"धत्तूरो मदकृत् तिक्तो जूकाज्वरकफापहः।\nउष्णो वर्णकरो कासकुष्ठकण्डूविनाशनः॥","source":{"text_grantha_name":"Bhavaprakasha Nighantu","varga_chapter":"Guduchyadi Varga","shloka_number":"Verse 85-86","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification":"A. Directly verified classical reference"}
]
def norm(x): return str(x or '').strip().lower().replace('ā','a').replace('ī','i').replace('ū','u').replace('ṃ','m').replace('ṁ','m')
def locate(plants,name):
    aliases={'Bhallataka':['bhallataka'],'Chitraka':['chitraka']}
    return next((p for p in plants if norm(p.get('identity',{}).get('name')) in aliases.get(name,[norm(name)])),None)
def merge(p,r):
    p['category']=r['category'];p['syllabus_marker']=r['category']
    i=p.setdefault('identity',{});i.update({'name':r['name'],'sanskrit_name':r['name'],'botanical_name':r['botanical_name'],'family':r['family'],'english_name':r['english_name'],'synonyms':r['sanskrit_synonyms']})
    d=p.setdefault('dravya_guna',{});d.update({'rasa':[x.lower() for x in r['rasa']],'guna':[x.lower() for x in r['guna']],'virya':r['virya'].lower(),'vipaka':r['vipaka'].lower(),'prabhava':r['prabhava'],'karma':r['karma']})
    p.setdefault('dosha',{})['summary']=r['dosha']
    p.setdefault('identification',{}).update({'description':r['identification'],'identification_points':[r['identification']]})
    t=p.setdefault('therapeutics',{});t.update({'useful_part':[r['useful_part']],'indications':r['indications'],'therapeutic_actions':r['karma']})
    p['formulations']=[{'name':x,'dosage_form':'','indication':'','reference':''} for x in r['formulations']]
    c=p.setdefault('classical_reference',{});c.update({'shlokas':[r['shloka']],'nighantu_references':[f"{r['source']['text_grantha_name']}, {r['source']['varga_chapter']}, {r['source']['shloka_number']}"],'shloka_reference_status':r['verification'],'gemini_source_reference':r['source']})
    p.setdefault('metadata',{})['gemini_later_batches_reviewed']=True;p['metadata']['gemini_source_batches']=sorted(set(p['metadata'].get('gemini_source_batches',[])+[r['id']]))
    p['gemini_source_data']=r
plants=json.loads(DATA.read_text(encoding='utf-8'))
for r in RECORDS:
    p=locate(plants,r['name'])
    if p is None:
        if r['category']=='Supplementary':
            p={'id':r['name'].lower(),'order':None,'identity':{'name':r['name']}}
            plants.append(p)
        else: raise KeyError(r['name'])
    merge(p,r)
# remove duplicate records by normalized identity name, keeping first
seen=set();out=[]
for p in plants:
    k=norm(p.get('identity',{}).get('name'))
    if k and k not in seen: seen.add(k);out.append(p)
for p in out:
    if isinstance(p.get('order'),int) and 1<=p['order']<=97:p['category']='NCISM-97';p['syllabus_marker']='NCISM-97'
out.sort(key=lambda p:(0 if p.get('category')=='NCISM-97' else 1,p.get('order') if isinstance(p.get('order'),int) else 9999,norm(p.get('identity',{}).get('name'))))
assert sum(p.get('category')=='NCISM-97' for p in out)==97
assert all(any(p.get('gemini_source_data',{}).get('id')==i for p in out) for i in range(84,89))
DATA.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Gemini batches 84-88 applied.')
