import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'plants.json'
BATCH = {
'Guggulu': {'identity': {'botanical_name':'Commiphora wightii (Arn.) Bhandari','family':'Burseraceae','english_name':'Indian Bdellium / Guggul','synonyms':['Devadhupa','Koushika','Pura','Mahishaksha','Palankasha']},'therapeutics':{'useful_part':['purified oleo-gum resin (Shodhita Niryasa)'],'indications':['Amavata','Vatarakta','Medoroga','Sandhivata','Granthi/Arbuda','Kushta']},'dravya_guna':{'rasa':['tikta','katu','kashaya','madhura'],'guna':['laghu','ruksha','tikshna','vishada','sukshma','sara'],'virya':'ushna','vipaka':'katu','prabhava':'Vedanasthapana / Medohara / Rasayana','karma':['Medohara','Rasayana','Shothahara','Vedanasthapana','Vranaropana','Lekhana','Bhangasandhanakara']},'dosha':{'vata':'generally pacifies','pitta':'may increase; use according to context','kapha':'pacifies'},'formulations':[{'name':'Yogaraja Guggulu'},{'name':'Kaishora Guggulu'},{'name':'Kanchanara Guggulu'},{'name':'Triphala Guggulu'},{'name':'Simhanada Guggulu'}],'identification':{'description':'Irregular brownish-yellow translucent or sticky oleo-gum resin masses with strong balsamic aromatic odor.'},'classical_reference':{'shlokas':['गुग्गुलुर्विशदस्तिक्तो वीर्योष्णः पित्तलः सरः ।\nकषायः कटुकः पाके कटू रूक्षो लघुः परः ॥३५॥'],'nighantu_references':['Bhavaprakasha Nighantu, Karpuradi Varga, verses 35–36 (edition numbering may vary)'],'shloka_reference_status':'verified text/reference in searchable Bhavaprakasha recension; edition/page should be recorded separately'},'metadata':{'status':'classical_text_checked'}},
'Ashoka': {'identity': {'botanical_name':'Saraca asoca (Roxb.) Willd.','family':'Fabaceae','english_name':'Ashoka Tree','synonyms':['Hemapushpa','Kankelli','Vamadhara','Pindapushpa']},'therapeutics':{'useful_part':['stem bark (Twak)','seeds (Bija)','flowers (Pushpa)'],'indications':['Asrigdara','Pradara','Yoniroga','Daha','Trishna','Apachi']},'dravya_guna':{'rasa':['kashaya','tikta'],'guna':['laghu','ruksha'],'virya':'sheeta','vipaka':'katu','prabhava':'Asrigdarahara / Stri-rogahara','karma':['Asrigdarahara','Garbhashaya-shothahara','Varnya','Hridya','Vranaropana','Sangrahi']},'dosha':{'vata':'generally not aggravating','pitta':'pacifies','kapha':'pacifies'},'formulations':[{'name':'Ashokarishta'},{'name':'Ashoka Ghrita'},{'name':'Ashokaksheerapaka'},{'name':'Chandanasava'}],'identification':{'description':'Stem bark pieces are channelled or curved, with rough greyish-brown outer surface and reddish-brown inner surface; strongly astringent.'},'classical_reference':{'shlokas':['अशोकः शीतलस्तिक्तो ग्राही वर्ण्यः कषायकः ।\nदोषापचीतृषादाहकृमिशोषविषापहः ॥'],'nighantu_references':['Bhavaprakasha Nighantu, Vatadi Varga, verses 47–48'],'shloka_reference_status':'reference verified; searchable text supports the core verse, but edition-level transcription should be checked'},'metadata':{'status':'classical_text_checked'}},
'Bala': {'identity': {'botanical_name':'Sida cordifolia L.','family':'Malvaceae','english_name':'Country Mallow','synonyms':['Vatyalika','Batyala','Kharayashtika','Bhadra']},'therapeutics':{'useful_part':['root','seeds','whole plant (Panchanga)'],'indications':['Vatavyadhi','Kshaya','Klaibya','Raktapitta','Daurbalya']},'dravya_guna':{'rasa':['madhura'],'guna':['guru','snigdha','picchila'],'virya':'sheeta','vipaka':'madhura','prabhava':'Balya / Vrishya / Vataharanam','karma':['Balya','Brimhana','Vrishya','Vatashamaka','Prajasthapana','Ojavardhaka']},'dosha':{'vata':'pacifies','pitta':'generally pacifies','kapha':'may increase'},'formulations':[{'name':'Balarishta'},{'name':'Bala Taila'},{'name':'Kshirabala Taila'},{'name':'Baladi Kwatha'}],'identification':{'description':'Subshrub with cylindrical taproot, cordate velvety leaves and yellow solitary flowers; seeds are characteristic.'},'classical_reference':{'shlokas':[],'nighantu_references':['Bhavaprakasha Nighantu, Guduchyadi Varga — exact verse requires edition-level verification'],'shloka_reference_status':'needs_verification'},'metadata':{'status':'structured_data_added_classical_text_pending'}},
'Punarnava': {'identity': {'botanical_name':'Boerhaavia diffusa L.','family':'Nyctaginaceae','english_name':'Spreading Hogweed','synonyms':['Shothaghni','Raktapunarnava','Varshabhu','Kathillaka','Prithvi']},'therapeutics':{'useful_part':['root','whole plant (Panchanga)'],'indications':['Shotha','Pandu','Vrikkaroga','Hridroga with swelling','Udara Roga']},'dravya_guna':{'rasa':['madhura','tikta','kashaya'],'guna':['laghu','ruksha'],'virya':'ushna','vipaka':'madhura','prabhava':'Shothahara / Mutrala','karma':['Shothahara','Mutrala','Hridya','Deepana','Anulomana','Rasayana','Panduhara']},'dosha':{'vata':'generally pacifies','pitta':'generally pacifies','kapha':'pacifies'},'formulations':[{'name':'Punarnavarishta'},{'name':'Punarnavadi Kwatha'},{'name':'Punarnavadi Mandoora'},{'name':'Punarnavasava'},{'name':'Punarnavadi Guggulu'}],'identification':{'description':'Diffusely branched perennial herb with stout root, green upper leaf surface, pale/whitish lower surface and small pinkish-red flowers.'},'classical_reference':{'shlokas':[],'nighantu_references':['Bhavaprakasha Nighantu, Guduchyadi Varga — exact verse requires edition-level verification'],'shloka_reference_status':'needs_verification'},'metadata':{'status':'structured_data_added_classical_text_pending'}},
'Eranda': {'identity': {'botanical_name':'Ricinus communis L.','family':'Euphorbiaceae','english_name':'Castor Oil Plant','synonyms':['Gandharvahasta','Vatari','Rubu','Chitra','Urubuka']},'therapeutics':{'useful_part':['root','leaves','seeds','seed oil (Eranda Taila)'],'indications':['Amavata','Vatavyadhi','Vibandha','Udavarta','Gulma']},'dravya_guna':{'rasa':['madhura','katu','kashaya'],'guna':['sukshma','tikshna','snigdha','sara','guru'],'virya':'ushna','vipaka':'madhura','prabhava':'Virechana / Vataharanam','karma':['Virechana','Vatashamaka','Vedanasthapana','Shothahara','Vrishya','Vayasthapana']},'dosha':{'vata':'pacifies','pitta':'may increase with excessive use','kapha':'generally pacifies'},'formulations':[{'name':'Eranda Saptaka Kwatha'},{'name':'Gandharvahastadi Taila'},{'name':'Eranda Taila'},{'name':'Rasnasaptaka Kwatha'},{'name':'Simhanada Guggulu'}],'identification':{'description':'Tall shrub with palmately lobed leaves, prickly three-celled fruits and smooth mottled seeds.'},'classical_reference':{'shlokas':[],'nighantu_references':['Bhavaprakasha Nighantu, Guduchyadi Varga — exact verse requires edition-level verification'],'shloka_reference_status':'needs_verification'},'metadata':{'status':'structured_data_added_classical_text_pending'}}}

def merge(d,s):
    for k,v in s.items():
        if isinstance(v,dict): merge(d.setdefault(k,{}),v)
        else: d[k]=v
plants=json.loads(DATA.read_text(encoding='utf-8'))
for p in plants:
    n=p.get('identity',{}).get('name','')
    if n in BATCH:
        merge(p,BATCH[n]); p.setdefault('metadata',{})['batch_49_53_added']=True
DATA.write_text(json.dumps(plants,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Applied legacy Gemini batch 49–53')
