import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'plants.json'
G=[
{"id":79,"classical_sanskrit_name":"Vatsanabha (वत्सनाभ)","botanical_name":"Aconitum ferox Wall. ex Ser.","family":"Ranunculaceae","english_common_name":"Monkshood / Indian Aconite","sanskrit_synonyms":["Visha (विष)","Amrita (अमृत)","Mahoushadha (महौषध)","Nagavisha (नागविष)","Maranachitta (मरणचित्त)"],"useful_part":"Purified Tuberous Root (Shodhita Kanda)","rasa":["Madhura","Katu","Tikta","Kashaya"],"guna":["Laghu","Ruksha","Tikshna","Vikasi","Vyavayi"],"virya":"Ushna","vipaka":"Katu","prabhava":"Yogavahi / Rasayana / Vedanasthapana","dosha_karma":"Tridoshara (Specially Kapha-Vatashamaka)","pharmacological_therapeutic_karma":["Yogavahi","Vedanasthapana","Jwarahara","Swedana","Deepana","Pachana","Rasayana","Vyavayi"],"important_indications":["Jwara (Acute & chronic fever / Intermittent fever)","Sandhishoola (Severe joint pain / Arthralgia)","Amavata (Rheumatoid arthritis)","Kasa (Cough / Bronchial spasm)","Shwasa (Dyspnea / Asthma)","Vatavyadhi (Neurological disorders / Sciatica)"],"important_formulations":["Tribhuvan Kirti Rasa","Anand Bhairav Rasa","Sanjivani Vati","Mrityunjaya Rasa","Mahavisagarbha Taila"],"identification_characters":"Conical tuberous root resembling a calf's navel, dark brown exterior with longitudinal wrinkles, whitish or pinkish internal fracture; highly toxic in unpurified state.","classical_shloka":"वत्सनाभो अतिविषवत् ज्ञेयः कफविषापहः।\nबल्यो रसायनो वृष्यो वातजिच्च महागुणः॥","shloka_source":{"text_grantha_name":"Bhavaprakasha Nighantu","sthana_section":"Nighantu Sthana","adhyaya":"N/A","varga_chapter":"Dhatvadi Varga / Vishadi Section","shloka_number":"Verse 208-210","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification_status":"A. Directly verified classical reference"},
{"id":80,"classical_sanskrit_name":"Katuki (कटुकी)","botanical_name":"Picrorhiza kurroa Royle ex Benth.","family":"Plantaginaceae (Scrophulariaceae)","english_common_name":"Picrorhiza / Gentian","sanskrit_synonyms":["Katurohini (कटुरोहिणी)","Tiktaka (तिक्तका)","Krishnabheda (कृष्णभेदा)","Matsyashakala (मत्स्यशकला)","Chakrangi (चक्राङ्गी)"],"useful_part":"Rhizome / Root (Kanda / Mula)","rasa":["Tikta"],"guna":["Laghu","Ruksha"],"virya":"Sheeta","vipaka":"Katu","prabhava":"Bhedana / Yakridrakshaka (Hepatoprotective) / Jwarahara","dosha_karma":"Kapha-Pittashamaka","pharmacological_therapeutic_karma":["Bhedana","Deepana","Pachana","Jwarahara","Yakriduttejaka","Raktashodhaka","Hridya"],"important_indications":["Kamala (Jaundice / Hepatitis)","Yakridroga (Hepatic & splenic disorders)","Jwara (Chronic fever / Malarial fever)","Kushta (Skin diseases / Dermatitis)","Vibandha (Constipation)","Raktapitta (Bleeding disorders)"],"important_formulations":["Arogyavardhini Vati","Katutrayadi Kwatha","Tiktaka Ghrita","Mahatiktaka Ghrita","Patoladi Kwatha"],"identification_characters":"Sub-cylindrical grayish-brown rhizomes marked with prominent circular leaf-scars and stem remnants, porous white internal fracture, intensely bitter persistent taste.","classical_shloka":"कटुकी कटुका तिक्ता शीता लघ्वी च दीपनी।\nकफपित्तज्वरास्रघ्नी बालेन्द्रियापहृत् सरः॥","shloka_source":{"text_grantha_name":"Bhavaprakasha Nighantu","sthana_section":"Nighantu Sthana","adhyaya":"N/A","varga_chapter":"Haritakyadi Varga","shloka_number":"Verse 140-141","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification_status":"A. Directly verified classical reference"},
{"id":81,"classical_sanskrit_name":"Kiratatikta (किराततिक्त)","botanical_name":"Swertia chirata Buch.-Ham.","family":"Gentianaceae","english_common_name":"Chirata / Bitter Stick","sanskrit_synonyms":["Bhunimba (भूनिम्ब)","Kirata (किरात)","Anaryatikta (अनार्यतिक्त)","Kandarutiktaka (काण्डतिक्त)","Ramasenaka (रामसेनक)"],"useful_part":"Whole Plant (Panchanga)","rasa":["Tikta"],"guna":["Laghu","Ruksha"],"virya":"Sheeta","vipaka":"Katu","prabhava":"Jwarahara (Agrya in Vishama Jwara) / Raktashodhaka","dosha_karma":"Kapha-Pittashamaka","pharmacological_therapeutic_karma":["Jwarahara","Deepana","Pachana","Raktashodhaka","Krimighna","Trishnanigrahana","Dahaprashamana"],"important_indications":["Vishama Jwara (Malarial / Relapsing / Typhoid fever)","Kamala (Jaundice)","Kushta (Skin diseases)","Agnimandya (Loss of appetite)","Trishna (Excessive thirst)","Prameha (Metabolic disorders / Diabetes)"],"important_formulations":["Sudarshana Churna","Kiratadi Kwatha","Mahasudarshana Ghanvati","Bhunimbadi Kwatha","Chirayita Ghanvati"],"identification_characters":"Purplish-brown cylindrical stems with yellow pith, opposite decussate sessile leaves, 4-merous greenish-yellow flowers, intensely bitter taste throughout the plant.","classical_shloka":"किराततिक्तः शीतोऽनलकरो लघुः।\nतिक्तो शोथतृषादाहज्वरव्रणकफापहः॥","shloka_source":{"text_grantha_name":"Bhavaprakasha Nighantu","sthana_section":"Nighantu Sthana","adhyaya":"N/A","varga_chapter":"Haritakyadi Varga","shloka_number":"Verse 151-152","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification_status":"A. Directly verified classical reference"},
{"id":82,"classical_sanskrit_name":"Bhringaraja (भृङ्गराज)","botanical_name":"Eclipta alba (L.) Hassk.","family":"Asteraceae (Compositae)","english_common_name":"False Daisy","sanskrit_synonyms":["Markava (मार्कव)","Kesharaja (केशराज)","Bhringa (भृङ्ग)","Pitribhringi (पितृभृङ्गी)","Angaraka (अङ्गारक)"],"useful_part":"Whole Plant (Panchanga)","rasa":["Katu","Tikta"],"guna":["Laghu","Ruksha"],"virya":"Ushna","vipaka":"Katu","prabhava":"Keshya / Rasayana / Yakridrakshaka","dosha_karma":"Kapha-Vatashamaka","pharmacological_therapeutic_karma":["Keshya","Rasayana","Deepana","Pachana","Yakriduttejaka","Shothahara","Vishaghna","Vedanasthapana"],"important_indications":["Khalitya / Palitya (Hair fall / Premature greying)","Kamala (Jaundice / Hepatic dysfunction)","Yakridvriddhi (Hepatomegaly)","Shotha (Edema / Swelling)","Kasa (Cough)","Pandu (Anemia)"],"important_formulations":["Bhringaraja Taila","Mahabhringaraj Taila","Bhringarajasava","Shadbindu Taila","Bhringaraj Ghrita"],"identification_characters":"Prostrate or erect annual herb with appressed hairs, opposite lanceolate leaves, small solitary white ray-floreted head inflorescence, acrid bitter taste.","classical_shloka":"भृङ्गराजः कटुस्तिक्त उष्णो रूक्षः कफापहः।\nकेश्यस्त्वच्यः क्रिमिश्वासकासामशोथपाण्डुहृत्॥","shloka_source":{"text_grantha_name":"Bhavaprakasha Nighantu","sthana_section":"Nighantu Sthana","adhyaya":"N/A","varga_chapter":"Guduchyadi Varga","shloka_number":"Verse 240-241","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification_status":"A. Directly verified classical reference"},
{"id":83,"classical_sanskrit_name":"Kumkuma (कुङ्कुम)","botanical_name":"Crocus sativus L.","family":"Iridaceae","english_common_name":"Saffron","sanskrit_synonyms":["Kesara (केसर)","Kashmiraka (काश्मीरक)","Shonita (शोणित)","Varakesara (वरकेसर)","Vahni (वह्नि)"],"useful_part":"Stigma & Style (Keshara / Vartikagra)","rasa":["Tikta","Katu"],"guna":["Snigdha","Laghu"],"virya":"Ushna","vipaka":"Katu","prabhava":"Varnya / Keshya / Hridya / Stri-rogahara","dosha_karma":"Tridoshashamaka (Specially Kapha-Pittashamaka)","pharmacological_therapeutic_karma":["Varnya","Hridya","Vedanasthapana","Shothahara","Artavajanana","Vrishya","Vishaghna","Deepana"],"important_indications":["Mukhadushika (Acne vulgaris / Hyperpigmentation)","Varnya (Complexion enhancement)","Hridroga (Cardiac weakness / Angina)","Artavadushti (Dysmenorrhea / Oligomenorrhea)","Shiro-shoola (Headache / Migraine)","Kasa / Shwasa (Cough / Asthma)"],"important_formulations":["Kumkumadi Taila","Kumkumadi Lehya","Kesaradi Churna","Chandanadi Vati","Kasturyadi Gutika"],"identification_characters":"Dark reddish-orange tri-fid thread-like stigmas attached to a short yellow style top, intensely aromatic sweet odor, colors water or saliva deep golden-yellow.","classical_shloka":"कुङ्कुमं कटुकं तिक्तं उष्णं श्लेष्मसीरार्तिजित्।\nवर्ण्यं वृष्यं च शोषघ्नमग्निदीप्तिप्रदं परम्॥","shloka_source":{"text_grantha_name":"Bhavaprakasha Nighantu","sthana_section":"Nighantu Sthana","adhyaya":"N/A","varga_chapter":"Karpuradi Varga","shloka_number":"Verse 12-14","edition_publisher":"Chowkhamba Bharati Academy, Varanasi","page_number":"Needs checking against physical copy for exact page"},"verification_status":"A. Directly verified classical reference"}
]

def norm(x): return str(x or '').strip().lower().replace('ā','a').replace('ī','i').replace('ū','u').replace('ṃ','m').replace('ṁ','m')
alias={'Bhringaraja':['Bhringaraja','Bhrungaraja'],'Kumkuma':['Kumkum','Kumkuma'],'Vatsanabha':['Vatsanabha','Vatsanabh']}
plants=json.loads(DATA.read_text(encoding='utf-8'))
for g in G:
 name=g['classical_sanskrit_name'].split(' (')[0]
 wanted={norm(x) for x in alias.get(name,[name])}
 p=next((x for x in plants if norm(x.get('identity',{}).get('name')) in wanted),None)
 if name=='Kiratatikta':
  if p is None:
   p={'id':'kiratatikta','order':None,'category':'Supplementary','syllabus_marker':'Supplementary','identity':{'name':'Kiratatikta','sanskrit_name':'किराततिक्त','transliteration':'','botanical_name':'','family':'','english_name':'','hindi_name':'','regional_names':[],'synonyms':[]},'classification':{'kingdom':'Plantae'},'identification':{},'images':{},'dravya_guna':{},'dosha':{},'therapeutics':{},'formulations':[],'classical_reference':{},'phytochemistry':{},'modern_information':{},'student':{},'teacher':{},'doctor':{},'sources':[],'metadata':{}}
   plants.append(p)
  cat='Supplementary'
 else:
  if p is None: raise KeyError(name)
  cat='NCISM-97'
 p['category']=cat;p['syllabus_marker']=cat
 i=p.setdefault('identity',{});i.update({'botanical_name':g['botanical_name'],'family':g['family'],'english_name':g['english_common_name'],'sanskrit_name':name,'synonyms':g['sanskrit_synonyms']})
 d=p.setdefault('dravya_guna',{});d.update({'rasa':[x.lower() for x in g['rasa']],'guna':[x.lower() for x in g['guna']],'virya':g['virya'].lower(),'vipaka':g['vipaka'].lower(),'prabhava':g['prabhava'],'karma':g['pharmacological_therapeutic_karma']})
 p.setdefault('dosha',{})['summary']=g['dosha_karma']
 p.setdefault('identification',{}).update({'description':g['identification_characters'],'identification_points':[g['identification_characters']]})
 t=p.setdefault('therapeutics',{});t.update({'useful_part':[g['useful_part']],'indications':g['important_indications'],'therapeutic_actions':g['pharmacological_therapeutic_karma']})
 p['formulations']=[{'name':x,'dosage_form':'','indication':'','reference':''} for x in g['important_formulations']]
 c=p.setdefault('classical_reference',{});c.update({'shlokas':[g['classical_shloka']],'nighantu_references':[f"{g['shloka_source']['text_grantha_name']}, {g['shloka_source']['varga_chapter']}, {g['shloka_source']['shloka_number']}"],'shloka_reference_status':g['verification_status'],'gemini_source_reference':g['shloka_source']})
 p.setdefault('metadata',{})['gemini_later_batches_reviewed']=True;p['metadata']['gemini_source_batches']=sorted(set(p['metadata'].get('gemini_source_batches',[])+[g['id']]))
 p['gemini_source_data']=g
# retain unique master records and exact 97 NCISM set
seen=set();out=[]
for p in plants:
 k=norm(p.get('identity',{}).get('name'))
 if k and k not in seen:seen.add(k);out.append(p)
out.sort(key=lambda p:(0 if p.get('category')=='NCISM-97' else 1,p.get('order') if isinstance(p.get('order'),int) else 9999,norm(p.get('identity',{}).get('name'))))
assert sum(1 for p in out if p.get('category')=='NCISM-97')==97
assert all(any(p.get('gemini_source_data',{}).get('id')==i for p in out) for i in range(79,84))
DATA.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Full Gemini batches 79-83 merged into master database.')
